/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package OPP;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;

/**
 *
 * @author Soknan Poch
 */
public class Setting extends javax.swing.JFrame {

    /**
     * Creates new form Setting
     */
    public Setting() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lbSetting = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rdRed = new javax.swing.JRadioButton();
        rdGreen = new javax.swing.JRadioButton();
        rdYello = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tcBlack = new javax.swing.JRadioButton();
        tcWhite = new javax.swing.JRadioButton();
        tcPink = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtTitleTextSize = new javax.swing.JTextField();
        cbBold = new javax.swing.JCheckBox();
        cbItalic = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbSetting.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbSetting.setText("Setting");

        jLabel2.setText("Background");

        buttonGroup1.add(rdRed);
        rdRed.setText("Red");

        buttonGroup1.add(rdGreen);
        rdGreen.setText("Green");

        buttonGroup1.add(rdYello);
        rdYello.setText("Yellow");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Text Color");

        buttonGroup2.add(tcBlack);
        tcBlack.setText("Black");

        buttonGroup2.add(tcWhite);
        tcWhite.setText("White");

        buttonGroup2.add(tcPink);
        tcPink.setText("Pink");

        jLabel3.setText("Title Text Size");

        cbBold.setText("Bold");

        cbItalic.setText("Italic");

        jLabel4.setText("Text Style");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(rdRed, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rdGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdYello, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(267, 267, 267)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tcPink, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tcBlack, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tcWhite, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbItalic)
                                            .addComponent(cbBold)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(lbSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTitleTextSize, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbSetting)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcBlack)
                    .addComponent(rdRed)
                    .addComponent(cbBold))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdGreen)
                    .addComponent(tcWhite)
                    .addComponent(cbItalic))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcPink)
                    .addComponent(rdYello))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtTitleTextSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
    private void changeRadioTextColor(){
       if(SettingClass.textColor == Color.white){
           tcWhite.setSelected(true);
       }
       else if(SettingClass.textColor == Color.pink){
           tcPink.setSelected(true);
       }
       else{
           tcBlack.setSelected(true);
       }
}
    private void changeRadioBackground(){
        if(SettingClass.backgroundColor == Color.red){
            rdRed.setSelected(true);
        }
        else if(SettingClass.backgroundColor == Color.green){
            rdGreen.setSelected(true);
        }
        else{
            rdYello.setSelected(true); 
        }
    }
    private void changeCheckTextFontStyle(){
        switch (SettingClass.fontStyle) {
            case Font.PLAIN:
                cbBold.setSelected(false);
                cbItalic.setSelected(false);
                break;
            case Font.BOLD | Font.ITALIC:
                cbBold.setSelected(true);
                cbItalic.setSelected(true);
                break;
            case Font.BOLD:
                cbBold.setSelected(true);
                cbItalic.setSelected(false);
                break;
            case Font.ITALIC:
                cbBold.setSelected(false);
                cbItalic.setSelected(true);
                break;
        }
    }
    private void chooseBackgroundColor(){
        if(rdRed.isSelected()){
            SettingClass.backgroundColor = Color.red;
        }
        else if(rdGreen.isSelected()){
            SettingClass.backgroundColor = Color.green;
        }
        else{
            SettingClass.backgroundColor = Color.yellow;
        }
}
    private void chooseTextColor(){
        if(tcWhite.isSelected()){
            SettingClass.textColor = Color.white;
        }
        else if(tcPink.isSelected()){
            SettingClass.textColor = Color.pink;
        }
        else{
            SettingClass.textColor = Color.black;
        }   
}
    private void chooseTextStyle(){
        if(cbBold.isSelected() && cbItalic.isSelected()){
            SettingClass.fontStyle = Font.BOLD | Font.ITALIC;
        }
        else if(cbBold.isSelected()){
            SettingClass.fontStyle = Font.BOLD;
        }
        else if(cbItalic.isSelected()){
            SettingClass.fontStyle = Font.ITALIC;
        }
        else{
            SettingClass.fontStyle = Font.PLAIN;
        }
        
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Component[] components = {
            cbBold, cbItalic, jButton1, jLabel1, jLabel2, jLabel3, jLabel4, lbSetting,
            rdGreen, rdRed, rdYello, tcBlack, tcPink, tcWhite,
            txtTitleTextSize
        };
        this.getContentPane().setBackground(SettingClass.backgroundColor); 
        changeRadioBackground();
        changeRadioTextColor();
        changeCheckTextFontStyle();
        txtTitleTextSize.setText(SettingClass.titleTextSize + "");
        SettingClass.changeTextColor(SettingClass.textColor, components);
        SettingClass.changeTextSize(SettingClass.titleTextSize, components);
        SettingClass.changeTextStyle(SettingClass.fontStyle, components);
               
       

    }//GEN-LAST:event_formWindowOpened


    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        chooseBackgroundColor();
        chooseTextColor();
        SettingClass.titleTextSize = Integer.parseInt(txtTitleTextSize.getText());
        chooseTextStyle();
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Setting setting = new Setting();
                setting.setVisible(true);
                setting.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox cbBold;
    private javax.swing.JCheckBox cbItalic;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbSetting;
    private javax.swing.JRadioButton rdGreen;
    private javax.swing.JRadioButton rdRed;
    private javax.swing.JRadioButton rdYello;
    private javax.swing.JRadioButton tcBlack;
    private javax.swing.JRadioButton tcPink;
    private javax.swing.JRadioButton tcWhite;
    private javax.swing.JTextField txtTitleTextSize;
    // End of variables declaration//GEN-END:variables
}
